[package]
name = "rustofi"
version = "0.1.0"
authors = ["Kristopher Ruzic <krruzic@gmail.com>"]
edition = "2018"

[lib]
name = "rustofi"
path = "src/lib.rs"

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
subprocess = "0.1.18"
